Add helpful output from failed Jobs during deployment

diff --git a/.circleci/deploy_to_kubernetes b/.circleci/deploy_to_kubernetes
--- a/.circleci/deploy_to_kubernetes
+++ b/.circleci/deploy_to_kubernetes
@@ -37,7 +37,15 @@ do
 done
 
 echo "Waiting for jobs"
-kubectl wait --for=condition=complete -f $COLLECT_STATIC -f $MIGRATE_DB --timeout=180s
+if ! kubectl wait --for=condition=complete -f $COLLECT_STATIC -f $MIGRATE_DB --timeout=180s ; then
+  echo "Failed pods:"
+  kubectl get pods --field-selector=status.phase=Failed
+  FIRST_POD=$(kubectl get pods --field-selector=status.phase=Failed -o=name | head -n 1)
+  echo "
+Logs for failed pod $FIRST_POD:"
+    kubectl logs $FIRST_POD
+  exit 1
+fi
 
 echo "Deploying app"
 # shellcheck disable=SC2002 # Useless cat, https://www.shellcheck.net/wiki/SC2002
